url = "http://api.lora.aprs.rf.guru"
call = "ON3URE-5"
aprs_host = "belgium.aprs2.net"
aprs_port = 14580
passcode = "23996" # https://apps.magicbug.co.uk/passcode/index.php/passcode
latitude = 51.151965
longitude = 2.765446
altitude = 45
comment = "https://rf.guru LoraAPRSGateway v0.1"
symbol = "La"
rf_guru_token = "whatever"
